name: 功能请求 | Feature Request
description: 提议新功能或改进 | Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提出新功能建议!请尽可能提供详细信息。
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: 问题陈述 | Problem Statement
      description: 你的功能请求是否与某个问题相关? | Is your feature request related to a problem?
      placeholder: |
        我在使用时总是遇到...
        I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提议的解决方案 | Proposed Solution
      description: 描述你想要的解决方案 | Describe the solution you'd like
      placeholder: |
        我希望看到...
        I would like to see...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: 使用示例 | Usage Example
      description: 展示你将如何使用这个功能 | Show how you would use this feature
      placeholder: |
        ```python
        from xhshow import Xhshow

        client = Xhshow()
        # 新功能的使用示例 | Example of how the new feature would work
        result = client.new_feature(...)
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 考虑过的替代方案 | Alternatives Considered
      description: 你考虑过的任何替代解决方案 | Any alternative solutions or features you've considered
      placeholder: |
        我还考虑过...
        I also thought about...

  - type: dropdown
    id: breaking
    attributes:
      label: 破坏性变更 | Breaking Changes
      description: 这个功能是否需要破坏性变更? | Would this feature require breaking changes?
      options:
        - "否 - 完全向后兼容 | No - Fully backward compatible"
        - "是 - 会破坏现有代码 | Yes - Would break existing code"
        - "不确定 | Not sure"
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: 兼容性确认 | Compatibility Confirmation
      description: 重要的兼容性考虑 | Important compatibility considerations
      options:
        - label: 此功能必须保持与现有版本的完全向后兼容 | This feature must maintain full backward compatibility
          required: false
        - label: 我已确认此功能不会与现有功能冲突 | I have checked that this feature doesn't conflict with existing functionality
          required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息 | Additional Context
      description: 添加其他信息、截图或示例 | Add any other context, screenshots, or examples
